# Generated by Django 3.1 on 2020-08-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Article title', max_length=50)),
                ('date', models.DateField()),
                ('image', models.ImageField(default='default.jpg', upload_to='image/')),
                ('text', models.TextField(default='text')),
            ],
        ),
    ]
