# Generated by Django 3.1 on 2020-08-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200824_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_imgs/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Article title', max_length=100),
        ),
    ]
